### ISSUE TITLE
Doesn't work with python 3.5

### ISSUE THREAD

**Issue by romanesko** [paulchakravarti/pgwrap#1]
```Collecting http://pypi.python.org/packages/source/p/pgwrap/pgwrap-0.7.tar.gz
  Downloading pgwrap-0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-283ru0l4-build/setup.py", line 10, in <module>
        long_description = file("README").read()
    NameError: name 'file' is not defined
```

**Comment by divmgl** [comment]
+1 to this

**Comment by paulc** [comment]
I've never tested this with Python 3 - I suspect that there are lots of implicit encoding issues that would stop this working. I'll try to have a look at this when I get a chance.

**Comment by paulc** [comment]
Latest version now supports Python 3
